version: "3.9"
services:

  web:
    restart: always
    build: .
    command: ["bash", "./start.sh"]
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
