# Generated by Django 4.2.4 on 2023-08-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
